### ISSUE TITLE
Add Python Environment File 

### ISSUE THREAD

**Issue by WillyChap** [JulioTBacmeister/PyRegridding#1]
It would be great to get a .yaml with a build environment! Thus far the stock standard NCAR/CISL envs (i.e. npl-2023b) don't seem to do the trick.

**Comment by JulioTBacmeister** [comment]
Hi Will I am using NPL 2022b or in command line form 

module load conda
conda activate npl-2022b
./DrvRegrid.py --year=2021 --month=6 --day=99 --hour=99 --Dst='Arctic' --DstVgrid='L32'

**Comment by WillyChap** [comment]
Yep... write after I wrote this issue I saw that, I don't know how I missed that....
